# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textspeech.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gtts import gTTS 
import os

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(524, 427)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 40, 311, 51))
        self.label.setStyleSheet("font: 24pt \"Forte\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 271, 31))
        self.label_2.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.field = QtWidgets.QTextEdit(Dialog)
        self.field.setGeometry(QtCore.QRect(70, 160, 401, 201))
        self.field.setStyleSheet("font: 11pt \"Arial\";")
        self.field.setObjectName("field")
        self.btn = QtWidgets.QPushButton(Dialog)
        self.btn.setGeometry(QtCore.QRect(220, 380, 75, 31))
        self.btn.setStyleSheet("font: 14pt \"Arial Rounded MT Bold\";")
        self.btn.setObjectName("btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.btn.clicked.connect(self.speak)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Convert Text To Speech"))
        self.label_2.setText(_translate("Dialog", "Enter Text you wanna hear"))
        self.btn.setText(_translate("Dialog", "Go!"))

    def speak(self):
        mytext = self.field.toPlainText()
        language = 'hi'
        myobj = gTTS(text=mytext, lang=language, slow=False) 
        myobj.save("sound.mp3") 
        os.system("start sound.mp3") 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
